"""empty message

Revision ID: 15a5b1c4aeee
Revises: f167ab224bc9
Create Date: 2019-03-05 13:48:07.220751

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '15a5b1c4aeee'
down_revision = 'f167ab224bc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Event', sa.Column('ageRestriction', sa.Integer(), nullable=True))
    op.add_column('Event', sa.Column('description', sa.String(), nullable=True))
    op.add_column('Event', sa.Column('enddate', sa.TIMESTAMP(), nullable=True))
    op.add_column('Event', sa.Column('facebookEventUrl', sa.String(), nullable=True))
    op.add_column('Event', sa.Column('organizer', sa.String(), nullable=True))
    op.add_column('Event', sa.Column('picture', sa.String(), nullable=True))
    op.add_column('Event', sa.Column('reducedPrice', sa.Float(), nullable=True))
    op.add_column('Event', sa.Column('regularPrice', sa.Float(), nullable=True))
    op.add_column('Event', sa.Column('startdate', sa.TIMESTAMP(), nullable=True))
    op.add_column('Event', sa.Column('title', sa.String(), nullable=True))
    op.add_column('Event', sa.Column('venueId', sa.Integer(), nullable=True))
    op.add_column('Event', sa.Column('videoUrl', sa.String(), nullable=True))
    op.drop_column('Event', 'regularTicketPrice')
    op.drop_column('Event', 'endDate')
    op.drop_column('Event', 'startTime')
    op.drop_column('Event', 'ageLimit')
    op.drop_column('Event', 'venueID')
    op.drop_column('Event', 'beskrivelse')
    op.drop_column('Event', 'organizerName')
    op.drop_column('Event', 'reducedTicketPrice')
    op.drop_column('Event', 'facebookURL')
    op.drop_column('Event', 'startDate')
    op.drop_column('Event', 'pictureURL')
    op.drop_column('Event', 'titel')
    op.drop_column('Event', 'videosURL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Event', sa.Column('videosURL', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Event', sa.Column('titel', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Event', sa.Column('pictureURL', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Event', sa.Column('startDate', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('Event', sa.Column('facebookURL', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Event', sa.Column('reducedTicketPrice', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('Event', sa.Column('organizerName', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Event', sa.Column('beskrivelse', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Event', sa.Column('venueID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Event', sa.Column('ageLimit', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Event', sa.Column('startTime', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('Event', sa.Column('endDate', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('Event', sa.Column('regularTicketPrice', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('Event', 'videoUrl')
    op.drop_column('Event', 'venueId')
    op.drop_column('Event', 'title')
    op.drop_column('Event', 'startdate')
    op.drop_column('Event', 'regularPrice')
    op.drop_column('Event', 'reducedPrice')
    op.drop_column('Event', 'picture')
    op.drop_column('Event', 'organizer')
    op.drop_column('Event', 'facebookEventUrl')
    op.drop_column('Event', 'enddate')
    op.drop_column('Event', 'description')
    op.drop_column('Event', 'ageRestriction')

    # ### end Alembic commands ###
