"""empty message

Revision ID: 52631d29cf32
Revises: 2cd18d93587f
Create Date: 2019-02-19 15:43:18.046555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52631d29cf32'
down_revision = '2cd18d93587f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exEvent', sa.Column('name', sa.String(), nullable=True))
    op.drop_column('exEvent', 'titel')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exEvent', sa.Column('titel', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('exEvent', 'name')
    # ### end Alembic commands ###
