"""empty message

Revision ID: 9783d9cec395
Revises: 15a5b1c4aeee
Create Date: 2019-03-12 11:30:28.243730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9783d9cec395'
down_revision = '15a5b1c4aeee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Event', 'organizerID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Event', sa.Column('organizerID', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
