"""empty message

Revision ID: c9aa54f7b95e
Revises: 
Create Date: 2019-03-22 11:10:50.477743

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'c9aa54f7b95e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Event',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('FID', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('startdate', sa.TIMESTAMP(), nullable=True),
    sa.Column('enddate', sa.TIMESTAMP(), nullable=True),
    sa.Column('isRepetition', sa.BOOLEAN(), nullable=True),
    sa.Column('venueName', sa.String(), nullable=True),
    sa.Column('venueCoordinates', geoalchemy2.types.Geography(geometry_type='POINT'), nullable=True),
    sa.Column('venueAddress', sa.String(), nullable=True),
    sa.Column('venueId', sa.Integer(), nullable=True),
    sa.Column('organizer', sa.String(), nullable=True),
    sa.Column('organizerWebsite', sa.String(), nullable=True),
    sa.Column('ageRestriction', sa.Integer(), nullable=True),
    sa.Column('regularPrice', sa.Float(), nullable=True),
    sa.Column('reducedPrice', sa.Float(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('category_name', sa.String(), nullable=True),
    sa.Column('picture', sa.String(), nullable=True),
    sa.Column('listPictureURL', sa.String(), nullable=True),
    sa.Column('ticketsURL', sa.String(), nullable=True),
    sa.Column('moreInfoURL', sa.String(), nullable=True),
    sa.Column('facebookEventUrl', sa.String(), nullable=True),
    sa.Column('videoUrl', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_Event_FID'), 'Event', ['FID'], unique=False)
    op.create_index(op.f('ix_Event_ID'), 'Event', ['ID'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Event_ID'), table_name='Event')
    op.drop_index(op.f('ix_Event_FID'), table_name='Event')
    op.drop_table('Event')
    # ### end Alembic commands ###
