"""empty message

Revision ID: d46227888ebf
Revises: 52631d29cf32
Create Date: 2019-02-26 12:18:20.659678

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2 #added manualy to
from geoalchemy2.types import Geography


# revision identifiers, used by Alembic.
revision = 'd46227888ebf'
down_revision = '52631d29cf32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Event',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('titel', sa.String(), nullable=True),
    sa.Column('beskrivelse', sa.String(), nullable=True),
    sa.Column('startDate', sa.DATE(), nullable=True),
    sa.Column('startTime', sa.TIME(), nullable=True),
    sa.Column('endDate', sa.DATE(), nullable=True),
    sa.Column('isRepetition', sa.BOOLEAN(), nullable=True),
    sa.Column('venueName', sa.String(), nullable=True),
    sa.Column('venueCoordinates', Geography(geometry_type='POINT'), nullable=True),
    sa.Column('venueAddress', sa.String(), nullable=True),
    sa.Column('venueID', sa.Integer(), nullable=True),
    sa.Column('organizerID', sa.Integer(), nullable=True),
    sa.Column('organizerName', sa.String(), nullable=True),
    sa.Column('organizerWebsite', sa.String(), nullable=True),
    sa.Column('ageLimit', sa.Integer(), nullable=True),
    sa.Column('regularTicketPrice', sa.Float(), nullable=True),
    sa.Column('reducedTicketPrice', sa.Float(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('category_name', sa.String(), nullable=True),
    sa.Column('pictureURL', sa.String(), nullable=True),
    sa.Column('listPictureURL', sa.String(), nullable=True),
    sa.Column('ticketsURL', sa.String(), nullable=True),
    sa.Column('moreInfoURL', sa.String(), nullable=True),
    sa.Column('facebookURL', sa.String(), nullable=True),
    sa.Column('videosURL', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.drop_table('exEvent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exEvent',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"exEvent_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('desc', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='exEvent_pkey')
    )
    op.drop_table('Event')
    # ### end Alembic commands ###
