"""empty message

Revision ID: f167ab224bc9
Revises: d46227888ebf
Create Date: 2019-03-05 10:40:16.258791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f167ab224bc9'
down_revision = 'd46227888ebf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Event', sa.Column('FID', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_Event_FID'), 'Event', ['FID'], unique=False)
    op.create_index(op.f('ix_Event_ID'), 'Event', ['ID'], unique=False)
    op.drop_index('idx_Event_venueCoordinates', table_name='Event')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_Event_venueCoordinates', 'Event', ['venueCoordinates'], unique=False)
    op.drop_index(op.f('ix_Event_ID'), table_name='Event')
    op.drop_index(op.f('ix_Event_FID'), table_name='Event')
    op.drop_column('Event', 'FID')

    # ### end Alembic commands ###
